### PR TITLE
otel cosmos schema: cleanups and comments

### PR DESCRIPTION
**Pull request by lmolkova**
1. I suggest starting with database conventions and remove `rntbd` - it's a protocol and its spans AFAIK would not have `db.` attributes 

2.  Make sure to validate yaml file and generate <semconv> tables with following command (works best under WSL)
```
docker run -v /mnt/<path/to>/opentelemetry-specification/semantic_conventions:/source -v /mnt/<path/to>/opentelemetry-specification/specification:/dst otel/semconvgen:latest -f /source markdown -md /dst
```
3. Some random feedback points:
    - `request_content_length_bytes` -> `request_content_length` - otel conventions omit bytes and use using consistently. 
    - `regions_contacted` -> should we remove it? I don't  see it's being populated and I think it should be available through cosmos diagnostics and network spans.
    - `retry_count` - please describe it well and make sure to describe the case when logical call involved multiple nested network calls.
    - `item_count` - should it be populated when working with 1 operation ?
    - activity_ids - please remove them. SDK can still populate attributes, but do you really need to spec it? what for?
    - `operation_type` - why is it needed? put `read`/`write` into `db.operation` and method name (`ReadItemAsync`) into span name

### CODE REVIEW

**Comment by sourabh1007** [comment]
> 1. I suggest starting with database conventions and remove `rntbd` - it's a protocol and its spans AFAIK would not have `db.` attributes
> 2. Make sure to validate yaml file and generate  tables with following command (works best under WSL)
> 
> ```
> docker run -v /mnt/<path/to>/opentelemetry-specification/semantic_conventions:/source -v /mnt/<path/to>/opentelemetry-specification/specification:/dst otel/semconvgen:latest -f /source markdown -md /dst
> ```
> 
> 3. Some random feedback points:
>    
>    * `request_content_length_bytes` -> `request_content_length` - otel conventions omit bytes and use using consistently.
>    * `regions_contacted` -> should we remove it? I don't  see it's being populated and I think it should be available through cosmos diagnostics and network spans.
>    * `retry_count` - please describe it well and make sure to describe the case when logical call involved multiple nested network calls.
>    * `item_count` - should it be populated when working with 1 operation ?
>    * activity_ids - please remove them. SDK can still populate attributes, but do you really need to spec it? what for?
>    * `operation_type` - why is it needed? put `read`/`write` into `db.operation` and method name (`ReadItemAsync`) into span name

1. `rntbd `calls are network calls similar to http calls. Hence followed the same convention i.e <protocol>.<attribute_name>. ref. https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#common-attributes

3 
* `request_content_length_bytes` => tells that this value is in bytes. So, documentation is the only way to tell the unit of measurement?
*  `regions_contacted` -> it always gets populated (other than multi master account and for this also we are fixing it)
image

*  `retry_count`  -> agree
* `item_count` -> It comes into picture only in case of queries and changefeed operations otherwise this attribute won't be present.
* activity_ids -> 
| db.cosmosdb.activity_id | Guid |  Unique Id for the operation and can be helpful to debug particular operation in backend logs  |
| db.cosmosdb.correlated_activity_id| Guid | It will be populated only in case of query operation to allow correlating query pages retrieved for the same multi-page or cross-partition query. |

*`operation_type` -> as per db conventions, db.operation contains operation name, hence introduced this attribute to have operation type.

**Comment by lmolkova** [comment]
> rntbd calls are network calls similar to http calls. Hence followed the same convention i.e .<attribute_name>. ref. https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#common-attributes

All semantic conventions defined in database.yaml and md files are **database** converntions. They MUST have db.system and other db attributes defined. You can't define protocol calls in this file. Let's separate this work and address protocol in a different Pr in a different file.


> request_content_length_bytes

We're trying to align all OpenTelemtery attributes across all spec, so that if payload size is reported, it's always in bytes. this'd apply for HTTP, messaging and other semantic conventions. For example, we're going to resolve this https://github.com/open-telemetry/opentelemetry-specification/issues/1053 and remove bytes where thay are still are.

So otel users don't need to know what cosmos puts there - they know that all telemetry they have reports bytes consistently.

**Comment by lmolkova** [comment]
> regions_contacted

is this needed assuming cosmos diagnostics is populated AND nested protocol-level calls are reported? I would avoid any duplication here. If this information is not duplicated, should it have array type?

**Comment by lmolkova** [comment]
> operation_type 
makes sense. Assuming there is a nested transport call with this information (maybe coming as `rntbd.method`), would it still be useful on operational span?


> activity_ids

I still don't understand why you need to spec them here. They're .net-specific and hopefully will go away in future, why document them here?

In Azure SDKs we define something similar and call it az.client_request_id (operation identifier) and az.service_request_id (individual try identifier returned by service). If you need something like this, can you reuse these or define something non-.NET specific?

**Pull request closed without merging**
